Ferlab-Ste-Justine/clin-proxy-api

.gitignore, README.md, package.json, pnpm-lock.yaml, src/index.js, staging.env
Updated dependencies and functional build and deploy process
=> Build + Deploy Process

src/services/aidbox.js, src/services/api/patient/index.js, src/services/api/patient/v1.js
Returns all patient resources from aidbox as `GET /Patient/{id}/$everything`
=> added patient resources endpoint

src/services/api/variant/schema/1.json, src/services/api/variant/sqon.js
@latch2112 See https://github.com/cr-ste-justine/clin-project/issues/143
=> composite filter (for score or quality)

src/services/api/variant/schema/1.json
removed gerp and added conservation_phylop
=> updated schema

src/services/api/variant/sqon.js
Addresses https://github.com/cr-ste-justine/clin-frontend/pull/87
=> fix for genericbool

src/services/api/variant/schema/1.json, src/services/elastic.js
default sort group by exomiserScore only for the current selected patient and then by VEP impact Score
@nyanofthemoon : Is there a better alternative ?  I don't like too much my code but my knowledge of JS is rusty a bit...
=> add exomiserScore to sort 

src/services/api/variant/schema/1.json
consult https://balsamiq-wireframes.appspot.com/?state={%22action%22:%22open%22,%22ids%22:[%221m8TETRKfErkNCPj3TVVa1dOKqMbplPWJ%22],%22userId%22:%22112485783634205812739%22}#
for new changes
=> new filter (metric, clinsig) and change of structure for filter

src/services/api/variant/schema/1.json
tested that frontend does not crash
=> config and min,max for numcomparison filter

src/services/api/helpers/acl.js, src/services/api/variant/sqon/dialect/es.js, src/services/api/variant/v1.js, src/services/elastic.js
This affects the following filter types:
- Generic
- GenericBoolean
- Specific
- NumericalComparison
=> update to es mapper for match clauses

pnpm-lock.yaml
=> deps update

src/services/api/helpers/validators.js, src/services/api/patient/v1.js, src/services/elastic.js
https://app.zenhub.com/workspaces/clin-sprints-5c59d2c907cc4d6f39e559c2/issues/cr-ste-justine/clin-project/195
=> #195 - Recherche avec plusieurs mots retourne aucun résultat

src/services/api/auth/index.js, src/services/keycloak.js
Added debug logging to keycloak client
=> Added debug logging to keycloak client

docker-compose-docker-local.yml
Missing bits for dockerized local gene service
=> Missing bits for dockerized local gene service

src/index.js
@latch2112 and the last hidden bug is squashed!
=> expired refresh token should return 401 and not 500

.github/workflows/publish_images.yml
Changed branch to push images to dev
=> Changed branch to push images to dev

docker-compose.yml, launch-docker-local.sh
Added integration to aidbox network
=> Added integration to aidbox network

docker-compose.yml
Changed placement to follow the convention introduced in the devops repo
=> Changed placement to follow the convention introduced in the devops repo

package.json, src/services/api/helpers/excel.js, src/services/api/helpers/excelUtils.js, src/services/api/service.js, src/services/api/variant/docs.json, src/services/api/variant/index.js, src/services/api/variant/v1.js
The added service receives an object from the frontend and streams an Excel file back
=> Service for Excel file generation

environments/common/configmaps/kustomization.yaml, environments/common/deployments.yml, environments/common/kustomization.yaml, environments/common/services.yml, environments/cq-qa/configmaps.yml, environments/cq-qa/deployments.yml, environments/cq-qa/ingresses.yml, environments/cq-qa/kustomization.yaml
=> Feature #390: Added kubernetes manifests

environments/common/configmaps/kustomization.yaml, environments/common/deployments.yml, environments/common/services.yml, environments/cq-qa/deployments.yml, environments/cq-qa/ingresses.yml
=> feat: #406 Added hpo orchestration

environments/cq-qa/configmaps.yml, environments/cq-qa/ingresses.yml
Migrated clin subdomain from clin.cqdg to clin
=> feat: #407 Migrated clin subdomain from clin.cqdg to clin

.github/workflows/unit_tests.yml, README.md
=> feat: Ferlab-Ste-Justine/clin-project#390 Added pipeline for unit tests

.github/workflows/commit_lint.yml, README.md
=> feat: Ferlab-Ste-Justine/clin-project#390 Added commit lint

.github/workflows/publish_images_sha.yml, .github/workflows/publish_images_tag.yml
Pipeline adjustment to push in docker teams organization
=> feat: #689 Pipeline adjustment to push in docker teams organization

app/package.json, app/src/services/api/patient/index.js, app/src/services/api/patient/v1.js, app/src/services/elastic.js
- Adds endpoint to retrieve gender and position info
=> feat: #749 Adds endpoint to retrieve gender and position

app/src/services/api/patient/v1.js, app/src/services/elastic.js
Linked: 
- https://github.com/Ferlab-Ste-Justine/clin-fhir-server/pull/42
- https://github.com/Ferlab-Ste-Justine/clin-frontend/pull/657
=> feat: #737 Support different search types
